<a href="https://colab.research.google.com/github/Judith-solomi/AI-and-ML-Assignments/blob/main/AI_ML_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AI/ML Assignment — Python, NumPy, Pandas & ML Foundations


- **Part A** — Python Revision
- **Part B** — NumPy
- **Part C** — Pandas
- **Part D** — ML Preparation

## Part A — Python Revision

### Q1. Find the mean of a list of numbers

In [ ]:
numbers = [12, 45, 23, 67, 34, 89, 10]

mean_value = sum(numbers) / len(numbers)

print("List:", numbers)
print("Mean:", mean_value)

List: [12, 45, 23, 67, 34, 89, 10]
Mean: 40.0

### Q2. Find the maximum and minimum values in a list

In [ ]:
numbers = [12, 45, 23, 67, 34, 89, 10]

print("List:", numbers)
print("Maximum:", max(numbers))
print("Minimum:", min(numbers))

List: [12, 45, 23, 67, 34, 89, 10]
Maximum: 89
Minimum: 10

### Q3. Count how many numbers are even and odd in a list

In [ ]:
numbers = [12, 45, 23, 67, 34, 89, 10, 5, 8, 21]

even_count = 0
odd_count = 0

for n in numbers:
    if n % 2 == 0:
        even_count += 1
    else:
        odd_count += 1

print("List:", numbers)
print("Even numbers:", even_count)
print("Odd numbers:", odd_count)

List: [12, 45, 23, 67, 34, 89, 10, 5, 8, 21]
Even numbers: 4
Odd numbers: 6

### Q4. Dictionary of 5 students and their marks — find the highest scorer

In [ ]:
students_marks = {
    "Amit": 78,
    "Priya": 92,
    "Rahul": 65,
    "Sneha": 88,
    "Karan": 74
}

topper = max(students_marks, key=students_marks.get)

print("Students and Marks:", students_marks)
print(f"Student with highest marks: {topper} ({students_marks[topper]} marks)")

Students and Marks: {'Amit': 78, 'Priya': 92, 'Rahul': 65, 'Sneha': 88, 'Karan': 74}
Student with highest marks: Priya (92 marks)

### Q5. Function that accepts a list of numbers and returns the average

In [ ]:
def find_average(numbers):
    """Return the average of a list of numbers."""
    return sum(numbers) / len(numbers)

sample_list = [10, 20, 30, 40, 50]
print("List:", sample_list)
print("Average:", find_average(sample_list))

List: [10, 20, 30, 40, 50]
Average: 30.0

## Part B — NumPy

### Q6. NumPy array of 10 numbers — mean, median, max, min, standard deviation

In [ ]:
import numpy as np

arr = np.array([12, 45, 23, 67, 34, 89, 10, 5, 8, 21])

print("Array:", arr)
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Array: [12 45 23 67 34 89 10  5  8 21]
Mean: 31.4
Median: 22.0
Maximum: 89
Minimum: 5
Standard Deviation: 26.522443326360413

### Q7. 3×3 NumPy matrix — addition, multiplication, transpose

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

print("\nAddition (A + B):\n", A + B)
print("\nElement-wise multiplication (A * B):\n", A * B)
print("\nMatrix multiplication (A @ B):\n", A @ B)
print("\nTranspose of A:\n", A.T)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise multiplication (A * B):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix multiplication (A @ B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

### Q8. Array of values 1–20 — slicing, even values, values greater than 10

In [ ]:
import numpy as np

arr = np.arange(1, 21)

print("Array:", arr)
print("First 5 values:", arr[:5])
print("Last 5 values:", arr[-5:])
print("Even values:", arr[arr % 2 == 0])
print("Values greater than 10:", arr[arr > 10])

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First 5 values: [1 2 3 4 5]
Last 5 values: [16 17 18 19 20]
Even values: [ 2  4  6  8 10 12 14 16 18 20]
Values greater than 10: [11 12 13 14 15 16 17 18 19 20]

## Part C — Pandas

### Q9. DataFrame of 10 students: Name, Age, Gender, Study_Hours, Attendance, Marks

In [ ]:
import pandas as pd

data = {
    "Name":        ["Amit", "Priya", "Rahul", "Sneha", "Karan",
                     "Divya", "Vikram", "Anjali", "Rohan", "Neha"],
    "Age":         [16, 17, 16, 17, 18, 16, 17, 18, 16, 17],
    "Gender":      ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "Study_Hours": [3, 6, 2, 7, 4, 8, 1, 5, 6, 3],
    "Attendance":  [85, 92, 60, 95, 78, 98, 55, 88, 90, 70],
    "Marks":       [65, 88, 45, 92, 70, 95, 40, 80, 85, 60]
}

df = pd.DataFrame(data)
df

     Name  Age Gender  Study_Hours  Attendance  Marks
0    Amit   16      M            3          85     65
1   Priya   17      F            6          92     88
2   Rahul   16      M            2          60     45
3   Sneha   17      F            7          95     92
4   Karan   18      M            4          78     70
5   Divya   16      F            8          98     95
6  Vikram   17      M            1          55     40
7  Anjali   18      F            5          88     80
8   Rohan   16      M            6          90     85
9    Neha   17      F            3          70     60

### Q10. Display head(), tail(), shape, columns, info(), describe()

In [ ]:
print("HEAD (first 5 rows):")
print(df.head())

print("\nTAIL (last 5 rows):")
print(df.tail())

print("\nSHAPE:", df.shape)

print("\nCOLUMNS:", df.columns.tolist())

print("\nINFO:")
df.info()

print("\nDESCRIBE:")
print(df.describe())

HEAD (first 5 rows):
    Name  Age Gender  Study_Hours  Attendance  Marks
0   Amit   16      M            3          85     65
1  Priya   17      F            6          92     88
2  Rahul   16      M            2          60     45
3  Sneha   17      F            7          95     92
4  Karan   18      M            4          78     70

TAIL (last 5 rows):
     Name  Age Gender  Study_Hours  Attendance  Marks
5   Divya   16      F            8          98     95
6  Vikram   17      M            1          55     40
7  Anjali   18      F            5          88     80
8   Rohan   16      M            6          90     85
9    Neha   17      F            3          70     60

SHAPE: (10, 6)

COLUMNS: ['Name', 'Age', 'Gender', 'Study_Hours', 'Attendance', 'Marks']

INFO:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         10 non-null     str
 1   Age          10 non-null     int64
 2   Gender       10 non-null     str
 3   Study_Hours  10 non-null     int64
 4   Attendance   10 non-null     int64
 5   Marks        10 non-null     int64
dtypes: int64(4), str(2)
memory usage: 612.0 bytes

DESCRIBE:
             Age  Study_Hours  Attendance      Marks
count  10.000000     10.00000    10.00000  10.000000
mean   16.800000      4.50000    81.10000  72.000000
std     0.788811      2.27303    14.90302  19.344824
min    16.000000      1.00000    55.00000  40.000000
25%    16.000000      3.00000    72.00000  61.250000
50%    17.000000      4.50000    86.50000  75.000000
75%    17.000000      6.00000    91.50000  87.250000
max    18.000000      8.00000    98.00000  95.000000

### Q11. Students whose Marks > 70

In [ ]:
high_scorers = df[df["Marks"] > 70]
high_scorers

     Name  Age Gender  Study_Hours  Attendance  Marks
1   Priya   17      F            6          92     88
3   Sneha   17      F            7          95     92
5   Divya   16      F            8          98     95
7  Anjali   18      F            5          88     80
8   Rohan   16      M            6          90     85

### Q12. Students whose Study_Hours > 5

In [ ]:
hard_workers = df[df["Study_Hours"] > 5]
hard_workers

    Name  Age Gender  Study_Hours  Attendance  Marks
1  Priya   17      F            6          92     88
3  Sneha   17      F            7          95     92
5  Divya   16      F            8          98     95
8  Rohan   16      M            6          90     85

### Q13. Average of Study_Hours, Attendance, and Marks

In [ ]:
print("Average Study Hours:", df["Study_Hours"].mean())
print("Average Attendance:", df["Attendance"].mean())
print("Average Marks:", df["Marks"].mean())

Average Study Hours: 4.5
Average Attendance: 81.1
Average Marks: 72.0

### Q14. Sort students by Marks — highest to lowest

In [ ]:
sorted_df = df.sort_values(by="Marks", ascending=False)
sorted_df

     Name  Age Gender  Study_Hours  Attendance  Marks
5   Divya   16      F            8          98     95
3   Sneha   17      F            7          95     92
1   Priya   17      F            6          92     88
8   Rohan   16      M            6          90     85
7  Anjali   18      F            5          88     80
4   Karan   18      M            4          78     70
0    Amit   16      M            3          85     65
9    Neha   17      F            3          70     60
2   Rahul   16      M            2          60     45
6  Vikram   17      M            1          55     40

### Q15. Check whether the dataset contains missing values

In [ ]:
print("Missing values per column:")
print(df.isnull().sum())

print("\nDoes the dataset have any missing values at all?", df.isnull().values.any())

Missing values per column:
Name           0
Age            0
Gender         0
Study_Hours    0
Attendance     0
Marks          0
dtype: int64

Does the dataset have any missing values at all? False

## Part D — ML Preparation

### Q16. What is Machine Learning?

Machine Learning is a way of teaching a computer to find patterns in data and use those
patterns to make predictions or decisions, instead of following a fixed set of rules that
a programmer writes by hand. We show the computer many examples (data), and it learns the
relationship between the inputs and the outputs on its own. Once it has learned this
relationship, it can make reasonably accurate predictions on new data it hasn't seen before.
For example, instead of manually coding rules to detect spam emails, we feed the model
thousands of emails labeled "spam" or "not spam", and it learns the patterns that separate
the two on its own.

### Q17. Difference between Feature and Target (with example)

- **Feature**: An input variable (column) used by the model to make a prediction. Features
  are also called independent variables. A dataset can have many features.
- **Target**: The output variable (column) that the model is trying to predict. It is also
  called the dependent variable or label. A dataset usually has one target column.

**Example**: Suppose we want to predict a student's exam **Marks** using their
**Study_Hours** and **Attendance**.
- Features → `Study_Hours`, `Attendance`
- Target → `Marks`

### Q18. Identify Features, Target, and Problem Type

| Study Hours | Attendance | Result |
|---|---|---|
| 2 | 60 | Fail |
| 3 | 65 | Fail |
| 4 | 70 | Pass |
| 6 | 80 | Pass |
| 8 | 90 | Pass |

- **Features**: `Study Hours`, `Attendance`
- **Target**: `Result`
- **Type of problem**: **Classification** — the target column (`Result`) contains discrete
  category labels ("Pass" / "Fail") rather than a continuous number, so this is a
  classification problem (specifically, binary classification).

### Q19. Classification vs Regression (with 2 real-world examples each)

- **Classification**: The model predicts a **category or class label** — a discrete output
  chosen from a fixed set of possibilities.
  - Example 1: Email spam detection → "Spam" or "Not Spam"
  - Example 2: Medical diagnosis → predicting whether a patient "Has Disease" or
    "No Disease" based on test results

- **Regression**: The model predicts a **continuous numeric value**.
  - Example 1: Predicting house prices based on area, location, and number of rooms
  - Example 2: Predicting tomorrow's temperature based on today's weather data

**In short**: if the output is a label/category → Classification; if the output is a
number on a continuous scale → Regression.

### Q20. Why do we split a dataset into Training data and Testing data?

We split the dataset so that we can check how well our model actually performs on data it
has never seen before, not just on the data it was trained on.

- The **training data** is used to let the model learn the patterns and relationships
  between the features and the target.
- The **testing data** is kept completely separate and is only used afterward, to evaluate
  the model's performance.

If we trained and tested the model on the exact same data, the model could simply
"memorize" the answers (a problem called **overfitting**) and appear to perform very well,
even though it would fail badly on new, real-world data. By testing on unseen data, we get
an honest estimate of how the model will perform in practice.